app/blueprints/accaunt/views.py
from flask import Blueprint, request, url_for, render_template
from flask_login import current_user, login_required 
from app.forms import UpdateAccountForm
import os


accaunt_blueprint = Blueprint('account', __name__, template_folder='templates')

@accaunt_blueprint.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about_me = form.about_me.data
        if form.old_password.data:
            current_user.password_hash = bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
        db.session.commit()
        flash('Your account has been updated!', 'success')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about_me.data = current_user.about_me
    image_file = url_for('static', filename='images/thumbnails/' + current_user.image_file)
    return render_template('accaunt/account.html', title='Account', image_file=image_file, form=form, user=current_user)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = f_name + random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/images/thumbnails/', picture_fn)
    # form_picture.save(picture_path)

    output_size = (128, 128)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

app/blueprints/general/views.py
from flask import Blueprint, render_template

general_blueprint = Blueprint('general', __name__, template_folder='templates')
@general_blueprint.route('/')
def to_main():
	return render_template('general/layout.html')

app/blueprints/post/views.py
from flask import Blueprint, redirect, request, render_template, flash, url_for, current_app
from app.models import User, Post
from app import db
from app.forms import PostForm, UpdatePostForm
from flask_login import login_required, current_user
from datetime import datetime
from config import ROWS_PER_PAGE


post_blueprint = Blueprint('posts', __name__, template_folder='templates')


@post_blueprint.route('/posts',methods=['GET', 'POST'])
def posts():
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.timestamp.desc())

    page = request.args.get('page', 1, type=int)
    posts = posts.paginate(page=page, per_page=ROWS_PER_PAGE)
    
    return render_template('post/posts.html', posts=posts, q=q)

@post_blueprint.route('/post/new', methods=['GET', 'POST'])
@login_required
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.body.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Post was created", category="info")
        return redirect(url_for('posts.posts'))

    return render_template('post/create_post.html', form=form)

@post_blueprint.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    form = UpdatePostForm()

    if current_user.username != post.author.username:
        flash("Its not your post", category="eror")
        return redirect(url_for('posts.posts'))

    elif form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.updatetime = datetime.utcnow()
        db.session.commit()
        flash("Post was updated", category="info")
        return redirect(url_for('posts.post', post_id=post.id))

    elif "delete" in request.form:
        db.session.delete(post)
        db.session.commit()
        flash("Post deleted", category="eror")
        return redirect(url_for('posts.posts'))

    return render_template('post/post.html', post=post, form=form)


@post_blueprint.route('/post/delete/<int:post_id>', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    pass

app/templates/_render_field.html
{% macro render_field(field) %}

 <dt>{{ field.label }}
 <dt>{{ field(class='form-control') }}
{% if field.errors %}
        {% for error in field.errors %}
            <span style="color: red;">{{ error }}</span>
         {% endfor %}
{% else %}
<br>
{% endif %}

{% endmacro %}

app/templates/edit.html
{% extends 'admin/model/edit.html' %}

{% block tail %}
    {{ super() }}
    <script src="http://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js"></script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>My blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">   
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
  </head >

  <body>
  <section class="hero is-primary is-fullheight">
      <div class="container">
        <div class="hero-head">
          <nav class="navbar">
            <div class="container">
              <div id="navbarMenuHeroA" class="navbar-menu">
                {% for cat, msg in get_flashed_messages(True) %}
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-{{cat}}">{{msg}}</li>
                  </ul>
                {%endfor %}
                <div class="navbar-end">
                    {% if current_user.is_anonymous %}
                    <a href="{{ url_for('auth.login') }}"  class="navbar-item">Login</a>
                    <a href="{{ url_for('auth.register') }}"  class="navbar-item">Register</a>
                    {% else %}
                    <a href="{{ url_for('account.account') }}"  class="navbar-item">Account</a>
                    <a href="{{ url_for('auth.logout') }}"  class="navbar-item">Log out</a>
                    <a href="{{ url_for('posts.add_post') }}" class="navbar-item">Create new post</a>

                    {% endif %}
                    <a href="{{ url_for('general.to_main') }}"   class="navbar-item">Main page</a>
                    <a href="{{ url_for('posts.posts') }}"   class="navbar-item">Posts</a>

                          </div>
                        </div>
                    </div>
                </nav>
            </div>

      </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>